# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 300775f50c4a6c4c3f4f40f267f4887890b07f77b6047f6b57e9095a283aa7e6ac1760555287f24bbcee71d61fea4ae9f93bbf21d43e2d4f9ae5ac75a0377616

test:
  secret_key_base: a159331bf8f32d2c056dfd770c7c3b8b19ea1f9a43c3c292ffcea052f5d8cc05edfc004348e4d8e5f6d51e16ab4b622ae8caa77815ad12e2152e6542b1e30333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 300775f50c4a6c4c3f4f40f267f4887890b07f77b6047f6b57e9095a283aa7e6ac1760555287f24bbcee71d61fea4ae9f93bbf21d43e2d4f9ae5ac75a0377616w
